# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StudentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddStudent = channel.unary_unary(
                '/student.StudentService/AddStudent',
                request_serializer=service__pb2.StudentRequest.SerializeToString,
                response_deserializer=service__pb2.StudentResponse.FromString,
                _registered_method=True)
        self.GetStudent = channel.unary_unary(
                '/student.StudentService/GetStudent',
                request_serializer=service__pb2.StudentId.SerializeToString,
                response_deserializer=service__pb2.StudentResponse.FromString,
                _registered_method=True)
        self.ListStudents = channel.unary_unary(
                '/student.StudentService/ListStudents',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.StudentList.FromString,
                _registered_method=True)
        self.UpdateStudent = channel.unary_unary(
                '/student.StudentService/UpdateStudent',
                request_serializer=service__pb2.StudentRequest.SerializeToString,
                response_deserializer=service__pb2.StudentResponse.FromString,
                _registered_method=True)
        self.DeleteStudent = channel.unary_unary(
                '/student.StudentService/DeleteStudent',
                request_serializer=service__pb2.StudentId.SerializeToString,
                response_deserializer=service__pb2.DeleteResponse.FromString,
                _registered_method=True)


class StudentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStudents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStudent,
                    request_deserializer=service__pb2.StudentRequest.FromString,
                    response_serializer=service__pb2.StudentResponse.SerializeToString,
            ),
            'GetStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudent,
                    request_deserializer=service__pb2.StudentId.FromString,
                    response_serializer=service__pb2.StudentResponse.SerializeToString,
            ),
            'ListStudents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStudents,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.StudentList.SerializeToString,
            ),
            'UpdateStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStudent,
                    request_deserializer=service__pb2.StudentRequest.FromString,
                    response_serializer=service__pb2.StudentResponse.SerializeToString,
            ),
            'DeleteStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStudent,
                    request_deserializer=service__pb2.StudentId.FromString,
                    response_serializer=service__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'student.StudentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('student.StudentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StudentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/student.StudentService/AddStudent',
            service__pb2.StudentRequest.SerializeToString,
            service__pb2.StudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/student.StudentService/GetStudent',
            service__pb2.StudentId.SerializeToString,
            service__pb2.StudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStudents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/student.StudentService/ListStudents',
            service__pb2.Empty.SerializeToString,
            service__pb2.StudentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/student.StudentService/UpdateStudent',
            service__pb2.StudentRequest.SerializeToString,
            service__pb2.StudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/student.StudentService/DeleteStudent',
            service__pb2.StudentId.SerializeToString,
            service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
